### ISSUE TITLE
rsyslog plugin

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd#18]
http://www.rsyslog.com/plugins/

**Comment by mathstuf** [comment]
To be clear this would be a plugin in rsyslog which forwards over EVENT.

**Comment by sardemff7** [comment]
Using the passive mode (since I do not think we can integrate the GLib main loop to rsyslog), it should be fairly easy. I looked a bit at the needed come, and since the headers are not installed (at least not here) it would have to live in the rsyslog repository.

You should probably wait for 1.0 to be out and the libeventd-plugin API to be stable (I may break it again once or twice).
Anyway, feel free to ping me if you [open a bug at rsyslog](https://github.com/rsyslog/rsyslog/issues).

**Comment by sardemff7** [comment]
Why am I talking about libeventd-plugin at all? libeventc API, of course. Which *should* be fairly stable already, actually.
