### ISSUE TITLE
how to set Anchor

### ISSUE THREAD

**Issue by Lompik** [sardemff7/eventd#26]
(using git 10558453e12264d8a65966c8f6b87c5323704262 )What I did was to set in `eventd.conf` to : 

    [Notification]
    Anchor=bottom left

When trying to use notify-send, `eventd` ends in a SEGFAULT (line 71 in src/libnkutils/src/token.c).

**Comment by sardemff7** [comment]
I found the issue. It was hidden because I never used non-defaults. :-D
The point is not the anchor itself, but instead the `[Notification]` section, which triggers code that unconditionally free some stuff.

I fixed it in 1940eba65a3febb4695c4f6071584d31079428ac. Not sure I will make a release right now, but it will be in 0.9.
