### ISSUE TITLE
Multiple tests fail with 'Unable to bind the IP socket: Error binding to address: Cannot assign requested address'

### ISSUE THREAD

**Issue by Coacher** [sardemff7/eventd#31]
Hello.

I am trying to make eventd's testsuite pass all tests, but relay-connection.test, libeventc-connection.test, and evp-connection.test fail all the time with `Unable to bind the IP socket: Error binding to address: Cannot assign requested address` error.

Here's the build log: https://paste.pound-python.org/show/wVbbUgrQig2qFd0hGeaE/
Here's the test-suite.log: https://paste.pound-python.org/show/e0AP8psd9dawXRt0vo1r/

I'm probably missing something obvious.

**Comment by sardemff7** [comment]
Do you have IPv6? eventd requires an IPv6-enabled system, even if you don’t have external connectivity.

**Comment by Coacher** [comment]
Indeed, I had IPv6 forcibly disabled, since my ISP doesn't have it.
After re-enabling IPv6 on my machine, all tests successfully pass.
Thank you very much for the help!

**Comment by Coacher** [comment]
> eventd requires an IPv6-enabled system, even if you don’t have external connectivity.

I am just starting to use eventd. Does it require IPv6 at runtime as well or just for tests?

**Comment by sardemff7** [comment]
I think it can work if you specify only IPv4 addresses or use UNIX sockets. Tests just use `localhost` which is basically “`::1` then `127.0.0.1` it you can” (because some systems bind IPv4 and v6 at the same time for `localhost` and the same goes for `any`).

I do not see a reliable way to add a runtime check for lack of IPv6 (one that would not have false positives). I’ll see to add a tests-specific switch to use `127.0.0.1` explicitly.

**Comment by sardemff7** [comment]
May you test the `wip/ipv6` branch please?

**Comment by Coacher** [comment]
Sure:
- IPv6 enabled in kernel and enabled in eventd: PASS
- IPv6 enabled in kernel and disabled in eventd: PASS
- IPv6 disabled in kernel and disabled in eventd: PASS

**Comment by sardemff7** [comment]
Thanks!
