### ISSUE TITLE
Image options in eventd.conf are ignored.

### ISSUE THREAD

**Issue by LeOtaku** [sardemff7/eventd#43]
Some options for the nd plugin are being ignored for me. I cannot set the size, anchor, etc. of images. 

This is my configuration:
```
[Queue default]
Anchor=top-right
Margin=20
Spacing=10
Limit=3
OldestAtAnchor=true

[Queue topleft]
Anchor=top-left
Margin=14
Spacing=10
Limit=5
OldestAtAnchor=true

[Queue top]
Anchor=top
Margin=14
Spacing=10
Limit=5

[Notification]
Text=${title}${message/^/\n}

[NotificationBubble]
Padding=20
Radius=0
Border=2
BorderColour=#35586c
BorderBlur=0
Colour=#151718

[NotificationText]
Font=GohuFont 11px
Colour=#FFF

[NotificationImage]
Width=100
Height=-1
FixedSize=false
Anchor=Bottom

[NotificationIcon]
Placement=Foreground
Height=25
```

**Comment by sardemff7** [comment]
Since I don’t know which image you are testing with, I could only guess the issue where from the `Height=-1` after looking at the code.
I pushed 03469685474d5e605d10ec5fd33728182d118056 and aa3c9d9f62852f7f9c8cf47b324175fb8d13f132 which should fix your issue.
Anchor issue was probably a side effect (you cannot align without the proper size) as it works for me with both `-1` and a specific height.

Can you try master and tell me if it’s fixed for you?

**Comment by LeOtaku** [comment]
No, still does not work on master for me.

**Comment by LeOtaku** [comment]
These are my compilation options, maybe I'm missing sth.:
```
mesonFlags = [
    "-Dnd-wayland=false"
    "-Dlibcanberra=false"
    "-Dipv6=false"
    "-Dsystemd=false"
    "-Dnotification-daemon=true"
    "-Dnd-xcb=true"
    "-Dnd-fbdev=true"
    "-Dim=false"
    "-Dsound=false"
    "-Dtts=false"
    "-Dwebhook=false"
    "-Dlibnotify=true"
    "-Dlibcanberra=false"
    "-Dgobject-introspection=false"
    "-Ddebug=false"

    "-Ddbussessionservicedir=etc/dbus"
];
```

**Comment by LeOtaku** [comment]
Here is my log:
[log](https://github.com/sardemff7/eventd/files/2192728/log.txt)

And the Images (For me it happens with any Image I use):
![white](https://user-images.githubusercontent.com/34915973/42693342-2c56e180-86af-11e8-9de2-97d5194ccf7d.png)
![13912255622_57551a3d76_k](https://user-images.githubusercontent.com/34915973/42693394-489a9c6a-86af-11e8-844f-c4f2d843d55d.jpg)

**Comment by sardemff7** [comment]
Hum, your images are bigger than the text, what do you expect exactly? Do you want the text at the bottom of the bubble?
If not, could you please send a screenshot of the bubble you get, and some mockup of the bubble you expect?

**Comment by LeOtaku** [comment]
Maybe I'm misunderstanding something here. Whatever I put in W/H the image is scaled to the same (tiny) size. I would like to configure said size so I am able to better see the image. (I'm not currently at my desk, 
please tell me if you still want the screen shot and mockup, or if this explains it)

**Comment by sardemff7** [comment]
Using your config, your wallpaper and the following command, here is a screenshot of the result here on master:
`eventc -u evp://localhost:9990 notification non-generic -d title=\"Someone\" -d message=\'1\\n2\\n333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333\\n4\\n\<span\ font=\"Monospace\"\>went\</span\>\ \<a\ href=\"http://example.org\"\>offline\</a\>\ \&lt\;\' -f image=test.jpg -d icon=\'theme:mpv\'`
![screenshot from 2018-07-13 19-51-41](https://user-images.githubusercontent.com/222943/42706222-54014186-86d6-11e8-85d7-6087064acea4.png)

**Comment by LeOtaku** [comment]
OK, that's definitely not what I get... (I'd be more than happy if it was) I only used notify-send though, so that could maybe be the problem? On the other hand, is the image intended to scale with the number of rows/columns? (I thought I had tried that, but maybe I haven't) I'll update you as soon as I get home.

**Comment by sardemff7** [comment]
Make sure to stop/kill all instances of eventd when you rebuild it. If you don’t launch it yourself, relying on D-Bus activation, then `eventctl stop` should be enough to stop it.

**Comment by LeOtaku** [comment]
Notify-send:
![notify-send](https://user-images.githubusercontent.com/34915973/42711122-1de7ccee-86e7-11e8-8ea9-f71d4a88d122.png)
Eventc/Yours:
![eventc](https://user-images.githubusercontent.com/34915973/42711192-452cf07c-86e7-11e8-8fe8-88343a1b21a4.png)

**Comment by LeOtaku** [comment]
Sorry, yours does actually look the exact same with my original config. I changed something. Notify-send still displays it wrong though. So the issue is with that plugin?

**Comment by LeOtaku** [comment]
Updated:
![eventc](https://user-images.githubusercontent.com/34915973/42711414-0ee50d00-86e8-11e8-84a9-c963691f72f4.png)

**Comment by sardemff7** [comment]
Ok, I see what is going on. With `notify-send` you send the image as the icon. Unless in `Overlay` style (with the icon as an emblem over the image), the icon does not replace the image if the image is lacking.
There are several solutions:
- Use `Image=icon` in `[Notification]` if you never intend to use other clients that may use both image and icon.
- Use the `image-path` hint: `notify-send -h string:image-path:/home/sardemff7/Loisirs/Images/avatar-LiliAnne_100.png`
  This is *not* spec-compliant because `image-path` is supposed to be a `file://` URI or a themed icon name, but almost all notification daemons support paths in here because wrong clients just means bug reports in daemons.
  “But I could do it right here, since I am writing it myself.” will you tell me… Sadly not, because `notify-send` does not accept `:` in hint data. ([I submitted a patch](https://bugzilla.gnome.org/show_bug.cgi?id=767655) but it’s more or less abandoned.)
- Change your `notify-send` calls to `eventc` calls.
  This is my preferred way because you can *do it right*, IOW, have specific event configurations for your specific use cases, instead of abusing the `libnotify` compatibility event. :-)

Anyway, the “icon replaces the image” is not written anywhere in the man pages (AFAIK), only in the [state of the art of notifications](https://www.eventd.org/state-art.html#eventd) page.
I will see where I can put some clarification that image and icon are two different entities to eventd. I think it is the only notification daemon to do that, but it is advertised as such, and clients are mainly libnotify users so it uses the `image-data` in most cases.

**Comment by LeOtaku** [comment]
Just setting the icon placement style to "Overlay" also seems to work. One last question: Is it by any chance possible to have the image displayed on the right side instead of the left? Btw. thank you very much for helping me!

**Comment by sardemff7** [comment]
Image is part of the “content” while icon is more like a “source identifier” to eventd nd. This is a design decision, so the image is on the left and icon either on the right or as an emblem in a corner over the image.
In the future, I want to implement a Right-to-Left option for RTL languages to keep the design coherent according to that idea. I may actually use the direction Pango can infer from the text, so I don’t have to add yet another option to the already long list, which means it’ll be harder to abuse too. :-)
If you don’t care much, you can just use Icon as image and be done with it.
ProTip: if you use specific events for your specific use cases, you can use icon as image on some and image + icon on others just as you see fit. ;-)
