### ISSUE TITLE
Port to libsoup3 API

### ISSUE THREAD

**Issue by thesamesam** [sardemff7/eventd#52]
libsoup2 is deprecated and unfortunately, while libsoup2 and libsoup3 can be installed in parallel, they can't be loaded within the same process - which causes problems if the other is loaded transitively by another dependency of some software.

Needs a port to libsoup3 API.

**Comment by sardemff7** [comment]
Good suggestion  
I am concerned that Debian stable doesn’t have libsoup3 yet so I will see if I can have compatibility for both at the same time without too much work

Out of curiosity: which software are you using that is affected?

**Comment by sardemff7** [comment]
Working on this, it appears I may have to drop libsoup entirely because it may not provide the necessary plumbing API any more…

The client side seems doable, but I’m not sure it’s worth keeping libsoup for that part only if I have to use another library for the server part.

However, I will think about splitting the server part as a separate plugin. I need to make sure the majority of the use cases won’t need the magic of auto-promoting to WebSocket on the regular socket though

**Comment by thesamesam** [comment]
> Good suggestion I am concerned that Debian stable doesn’t have libsoup3 yet so I will see if I can have compatibility for both at the same time without too much work

Thank you!

> 
> Out of curiosity: which software are you using that is affected?

I don't think we had an actual runtime problem with eventd, fortunately -- but gssdp for example as one of eventd's dependencies also supports libsoup so we had to keep them in lockstep wrt libsoup 2 (and not using 3 yet).

**Comment by sardemff7** [comment]
Done in v0.29.0, with a gssdp dependency bump too, enjoy :-)

**Comment by thesamesam** [comment]
Thank you!
